x-env: &local_variables
  NEO4J_URI: "${NEO4J_URI:-bolt://neo4j:7687}"
  NEO4J_USERNAME: "${NEO4J_USERNAME:-neo4j}"
  NEO4J_PASSWORD: "${NEO4J_PASSWORD:-password}"
  NEO4J_DATABASE: "${NEO4J_DATABASE:-neo4j}"
  # TODO; maybe not needed!
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_export_cypher_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_apoc_import_file_use_neo4j_config: "true"

x-service: &service
  networks:
    - shared
  restart: unless-stopped

services:
  neo4j:
    <<: *service
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      <<: *local_variables
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 2g
      NEO4J_server_memory_pagecache_size: 512m
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/dumps:/var/lib/neo4j/data/dumps
    healthcheck:
        test:
          [
            "CMD",
            "/var/lib/neo4j/bin/cypher-shell",
            "--non-interactive",
            "--format", "plain",
            "-a", "bolt://localhost:7687",
            "-u", "${NEO4J_USERNAME}",
            "-p", "${NEO4J_PASSWORD}",
            "RETURN 1;"
          ]
        interval: 15s
        timeout: 15s
        retries: 5
        start_period: 60s
    deploy:
      resources:
        limits:
          memory: 3g

  # Separate service for database initialization
  neo4j-init:
    image: neo4j:latest
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/dumps:/var/lib/neo4j/data/dumps
    environment:
      <<: *local_variables
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}

    entrypoint: >
      bash -c "
                set -e  # exit immediately on any error
      
                echo '[INFO] Loading neo4j...'
                neo4j-admin database load --verbose --overwrite-destination=true neo4j
                echo '[OK] Load complete.'
        "
    restart: "no"

  app:
    <<: *service
    build: .
    container_name: diploma-thesis-app
    ports:
      - "8000:8000"
    depends_on:
      neo4j-init:
        condition: service_completed_successfully
    volumes:
      - ./diploma_thesis/data:/app/diploma_thesis/data
      - ./diploma_thesis/web:/app/diploma_thesis/web
      - ./diploma_thesis/web/static:/app/static
      - ./diploma_thesis/web/templates:/app/templates
    environment:
      <<: *local_variables
    deploy:
      resources:
        limits:
          memory: 1g

networks:
  shared:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_dumps:
  neo4j_conf: