services:
  web:
    build: .
    container_name: diploma-thesis-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/diploma_thesis/data
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=1
    restart: unless-stopped
